add FW Scripts to extend DB
astlexander/hrd pull request #1
Opened 2022-09-17 18:48 UTC by astlexander

2022-09-17 18:53 UTC, astlexander commented
I have add FlyWay scripts to create DB accordantly to DB-schema showed in daily. 
In new directory "documentation" you can find screenshot of ERD Schema of created from PGAdmin

2022-09-21 10:06 UTC, AlecKotovichSAM reviewed
rename to jpeg

2022-09-21 10:09 UTC, AlecKotovichSAM commented on src/main/resources/db/migration/V1.4__rebuild_db_with_rename_role_table.sql
> +CREATE TABLE logon
Rename to login

2022-09-21 10:10 UTC, AlecKotovichSAM commented on src/main/resources/db/migration/V1.4__rebuild_db_with_rename_role_table.sql
> +ALTER TABLE logon
login

2022-09-21 11:27 UTC, AlecKotovichSAM requested changes
I made comments, please fix

2022-09-22 07:19 UTC, merged